linters:
    enable-all: true
    disable:
        - maligned
        - godot
        # TODO: fix these issues
        - errcheck
        - unconvert
        - structcheck
        - deadcode
        - gofmt
        - golint
        - megacheck
        - goimports
        - noctx
        - exhaustivestruct
        - gomnd

linters-settings:
    golint:
        min-confidence: 0.1

    funlen:
        lines: 120
        statements: 50

issues:
    exclude:
        - G104 # TODO: fix error check issues
