FROM alpine:3.7 AS builder

RUN apk add --update --no-cache ca-certificates


FROM alpine:3.7

COPY --from=builder /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/

ARG BUILD_DIR
ARG BINARY_NAME

COPY $BUILD_DIR/$BINARY_NAME /usr/local/bin/anchore-image-validator

RUN adduser -D anchore-image-validator
USER anchore-image-validator

ENTRYPOINT ["/usr/local/bin/anchore-image-validator"]
