version: 2.1

orbs:
  helm: banzaicloud/helm@0.0.6
jobs:
  build:
    docker:
      - image: cimg/go:1.13
        environment:
          GOFLAG: -mod=readlonly

    steps:
      - checkout

      - restore_cache:
          name: Restore build dependencies
          keys:
          - build-deps-v1-{{ .Branch }}-{{ checksum "Makefile" }}

      - restore_cache:
          name: Restore go dependencies
          keys:
            - go-mod-v1-{{ .Branch }}-{{ checksum "go.sum" }}

      - run:
            name: Build
            command: make build

      - run:
          name: Install license checker
          command: make bin/licensei

      - restore_cache:
          name: Restore licensei cache
          keys:
            - licensei-v1-{{ .Branch }}-{{ checksum "go.sum" }}

      - run:
          name: Download license information for dependencies
          command: make license-cache

      - run:
          name: Check dependency licenses
          command: make license-check

      - save_cache:
          name: Save go dependencies
          key: go-mod-v1-{{ .Branch }}-{{ checksum "go.sum" }}
          paths:
            - /home/circleci/go/pkg/mod

      - save_cache:
          key: licensei-v1-{{ .Branch }}-{{ checksum "go.sum" }}
          paths:
            - .licensei.cache

workflows:
  ci:
    jobs:
      - build
      - helm/lint-chart:
          name: Lint chart
          charts-dir: charts
          filters:
            branches:
              only: /.*/
            tags:
              only: /anchore-policy-validator\/\d+\.\d+\.\d+(?:-(?:dev|rc)\.\d+)?/
      - helm/publish-chart:
          name: Publish chart
          context: helm
          charts-dir: charts
          requires:
            - 'Lint chart'
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /anchore-policy-validator\/\d+\.\d+\.\d+(?:-(?:dev|rc)\.\d+)?/
