# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.10

    working_directory: /go/src/github.com/banzaicloud/anchore-image-validator
    steps:
      - checkout
      - run:
          name: Build
          command:
              make build
