apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: audits.security.banzaicloud.com
spec:
  group: security.banzaicloud.com
  version: v1alpha1
  names:
    kind: Audit
    plural: audits
    singular: audit
  scope: Cluster
  validation:
    openAPIV3Schema:
      properties:
        spec:
          required:
            - releaseName
            - resource
            - image
            - result
            - action
          properties:
            relaseName:
              type: string
            resource:
              type: string
            image:
              type: string
            result:
              type: string
            action:
              type: string