apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: whitelistitems.security.banzaicloud.com
spec:
  group: security.banzaicloud.com
  version: v1alpha1
  names:
    kind: WhiteListItem
    plural: whitelistitems
    singular: whitelistitem
    shortnames:
      - wl
  scope: Cluster
  validation:
    openAPIV3Schema:
      properties:
        spec:
          required:
            - releaseName
            - reason
            - creator
          properties:
            relaseName:
              type: string
            reason:
              type: string
            creator:
              type: string
  additionalPrinterColumns:
  - name: ReleaseName
    type: string
    JSONPath: .spec.releaseName
    priority: 1
  - name: Reason
    type: string
    JSONPath: .spec.readson
    priority: 2
  - name: Creator
    type: string
    JSONPath: .spec.creator
    priority: 3
