{{ if .Values.rbac.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "anchore-policy-validator.fullname" . }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ template "anchore-policy-validator.fullname" . }}-binding
roleRef:
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
  name: {{ template "anchore-policy-validator.fullname" . }}-role
subjects:
- kind: ServiceAccount
  name: {{ template "anchore-policy-validator.fullname" . }}
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ template "anchore-policy-validator.fullname" . }}-role
rules:
- apiGroups:
  - admissionregistration.k8s.io
  resources:
  - validatingwebhookconfigurations
  verbs:
  - get
- apiGroups:
  - ""
  resources:
  - pods
  - namespaces
  - secrets
  - configmaps
  verbs:
  - get
- apiGroups:
  - security.banzaicloud.com
  resources:
  - audits
  - whitelistitems
  verbs:
  - get
  - list
  - update
  - patch
  - create
{{ if .Values.rbac.psp.enabled }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: psp:{{ template "anchore-policy-validator.fullname" . }}
roleRef:
  kind: Role
  apiGroup: rbac.authorization.k8s.io
  name: psp:{{ template "anchore-policy-validator.fullname" . }}
subjects:
- kind: ServiceAccount
  namespace: {{ .Release.Namespace }}
  name: {{ template "anchore-policy-validator.fullname" . }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: psp:{{ template "anchore-policy-validator.fullname" . }}
rules:
- apiGroups:
  - policy
  resourceNames:
  - psp.imagevalidator
  resources:
  - podsecuritypolicies
  verbs:
  - use
{{ end }}
{{ end }}
