name: Docker Build
on:
  pull_request:
    branches: [master]
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"

jobs:
  docker:
    name: Docker
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build anchore-image-validator
        uses: docker/build-push-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.CR_PAT }}
          registry: ghcr.io
          repository: banzaicloud/anchore-image-validator
          dockerfile: Dockerfile
          tag_with_ref: true
          add_git_labels: true
          tags: latest
